import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r  from-[#CC4448] to-[#68147E] to-46% flex flex-col justify-between min-h-screen">
        <Toaster />
        {children}
        <footer className="flex min-h-[10%] h-[10%] justify-center bg-[#000000] bg-opacity-[20%] p-4">
        <h2>Copyright © 2024 NextLevel - All rights reserved</h2>
      </footer>
      </body>
    </html>
  );
}
